# Generated by Django 3.2.18 on 2023-04-10 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='users',
            new_name='user',
        ),
    ]
