# Generated by Django 3.2.12 on 2023-04-11 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_like_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='like_user',
            new_name='like_users',
        ),
    ]
